paths:
    baseImages: /var/dockmaster/baseImages
    images: /var/dockmaster/images
    repositories: /var/dockmaster/repositories

db:
    path: /var/dockmaster/data.db

schedule:
    check: 10s

logging:
    level: DEBUG
    file: /var/log/dockmaster.log
    period: daily
